# Generated by Django 5.1 on 2024-08-25 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professeur', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='classe',
            field=models.CharField(choices=[('Mathematique', 'Mathematique'), ('PC', 'PC'), ('EPS', 'EPS'), ('Anglais', 'Anglais'), ('SVT', 'SVT'), ('Philosophie', 'Philosophie'), ('Francais', 'Francais')], max_length=20, verbose_name='Matiere'),
        ),
    ]
