# Generated by Django 5.1 on 2024-08-25 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('professeur', '0002_alter_teacher_classe'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher',
            old_name='classe',
            new_name='matiere',
        ),
    ]
