# Generated by Django 5.1 on 2024-08-25 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professeur', '0003_rename_classe_teacher_matiere'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='gender',
            field=models.CharField(choices=[('m', 'Male'), ('f', 'Female')], max_length=10),
        ),
    ]
